# name: Check code quality
# on: [push]

# jobs:
#   code-quality:
#     strategy:
#       fail-fast: false
#       matrix:
#         python-version: [3.9]
#         poetry-version: [1.1.8]
#         os: [ubuntu-latest]
#     runs-on: ${{ matrix.os }}
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with: 
#           python-version: ${{ matrix.python-version }}
#       - name: Run image
#         uses: abatilo/actions-poetry@v2.0.0
#         with:
#           poetry-version: ${{ matrix.poetry-version }}
#       - name: Install dep
#         run: poetry install
#       - name: Run black
#         run: poetry run black . --check -l 120
#       - name: Run isort
#         run: poetry run isort . --check-only --profile black
#       - name: Run flake8
#         run: poetry run flake8 .
#       - name: Run bandit
#         run: poetry run bandit .
#       - name: Run safety
#         run: poetry run safety check
        
      
